---
- name: Create Node red Data folder
  file:
     path: /home/pi/docker-nodered
     state: directory
     group: pi
     owner: pi


- name: Run node-red container
  docker_container:
     network_mode: host
     name: node-red
     image: nodered/node-red:latest 
     ports: 
      - "1880:1880"
     volumes:
     - "/home/pi/docker-nodered:/data"